#
# Copyright (c) 2022 Airbyte, Inc., all rights reserved.
#


import json
import datetime
from re import sub
from typing import Dict, Generator

from airbyte_cdk.logger import AirbyteLogger
from airbyte_cdk.models import (
    AirbyteCatalog,
    AirbyteConnectionStatus,
    AirbyteMessage,
    AirbyteRecordMessage,
    AirbyteStream,
    ConfiguredAirbyteCatalog,
    Status,
    Type
    )
from airbyte_cdk.sources import Source

from google.oauth2 import service_account
from googleapiclient.discovery import build
import json
from collections import defaultdict
import source_google_calendar.utils as ut

class SourceGoogleCalendar(Source):
    def check(self, logger: AirbyteLogger, config: json) -> AirbyteConnectionStatus:
        """
        Tests if the input configuration can be used to successfully connect to the integration
            e.g: if a provided Stripe API token can be used to connect to the Stripe API.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteConnectionStatus indicating a Success or Failure
        """
        try:

            SERVICE_ACCOUNT_JSON = json.loads(config.get("credentials"))



            SCOPES = ["https://www.googleapis.com/auth/calendar.events.readonly"]



            credentials = service_account.Credentials.from_service_account_info(
                SERVICE_ACCOUNT_JSON, scopes=SCOPES
            )

            subject = 'jordan.young@trydatabook.com'
            delegated_credentials = credentials.with_subject(subject)
            service = build("calendar", "v3", credentials=delegated_credentials)


            events_result = (
            service.events()
            .list(
                calendarId=subject,  # account in question
                maxResults=None  # max results to surface
                # singleEvents=False,  # expand recurring events to instances of single events? True = yes
                # orderBy="startTime",  # How to order events?
            )
            .execute())

            return AirbyteConnectionStatus(status=Status.SUCCEEDED)
        except Exception as e:
            return AirbyteConnectionStatus(status=Status.FAILED, message=f"An exception occurred: {str(e)}")

    def discover(self, logger: AirbyteLogger, config: json) -> AirbyteCatalog:
        """
        Returns an AirbyteCatalog representing the available streams and fields in this integration.
        For example, given valid credentials to a Postgres database,
        returns an Airbyte catalog where each postgres table is a stream, and each table column is a field.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
        the properties of the spec.yaml file

        :return: AirbyteCatalog is an object describing a list of all available streams in this source.
            A stream is an AirbyteStream object that includes:
            - its stream name (or table name in the case of Postgres)
            - json_schema providing the specifications of expected schema for this stream (a list of columns described
            by their names and types)
        """
        streams = []

        stream_name = "google_calendar"  # Example
        json_schema = {  # Example
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {"data": {"type": "object"}},
        }

        # Not Implemented



        streams.append(AirbyteStream(name=stream_name, json_schema=json_schema))
        return AirbyteCatalog(streams=streams)

    def read(
        self, logger: AirbyteLogger, config: json, catalog: ConfiguredAirbyteCatalog, state: Dict[str, any]
    ) -> Generator[AirbyteMessage, None, None]:
        """
        Returns a generator of the AirbyteMessages generated by reading the source with the given configuration,
        catalog, and state.

        :param logger: Logging object to display debug/info/error to the logs
            (logs will not be accessible via airbyte UI if they are not passed to this logger)
        :param config: Json object containing the configuration of this source, content of this json is as specified in
            the properties of the spec.yaml file
        :param catalog: The input catalog is a ConfiguredAirbyteCatalog which is almost the same as AirbyteCatalog
            returned by discover(), but
        in addition, it's been configured in the UI! For each particular stream and field, there may have been provided
        with extra modifications such as: filtering streams and/or columns out, renaming some entities, etc
        :param state: When a Airbyte reads data from a source, it might need to keep a checkpoint cursor to resume
            replication in the future from that saved checkpoint.
            This is the object that is provided with state from previous runs and avoid replicating the entire set of
            data everytime.

        :return: A generator that produces a stream of AirbyteRecordMessage contained in AirbyteMessage object.
        """
        


        SERVICE_ACCOUNT_JSON = json.loads(config.get("credentials"))
        client_email = SERVICE_ACCOUNT_JSON.get('client_email')

        month_search_window_size = config.get('month_window_size')
        target_companies = json.loads(config.get('domains')).get('domains')
        subjects = json.loads(config.get("emails")).get('emails')

        SCOPES = ["https://www.googleapis.com/auth/calendar.events.readonly"]



        credentials = service_account.Credentials.from_service_account_info(
            SERVICE_ACCOUNT_JSON, scopes=SCOPES
        )


        now = datetime.datetime.utcnow()  # 'Z' indicates UTC time

        # gets a previous month and future month with respeect to right now based on the window size
        # e.g. window size = 1: 1 month in the past 1 month in the future
        past_month, future_month = ut.get_past_future_month(
            now, periods=month_search_window_size
        )

        # dictionary to hold metadata for a given event
        event_data = defaultdict(lambda: defaultdict(dict))

        for subject in subjects:


            try:
                ut.extract_calendar(
                    subject,
                    credentials,
                    event_data,
                    target_companies,
                    past_month,
                    future_month
                )
            except Exception as e:
                print(subject, "FAILED", e)



        stream_name = "google_calendar"  # Example
        data = {"data": event_data}  # Example

        # Not Implemented

        yield AirbyteMessage(
            type=Type.RECORD,
            record=AirbyteRecordMessage(stream=stream_name, data=data, emitted_at=int(datetime.datetime.now().timestamp()) * 1000),
        )
